# This file was generated by GoReleaser. DO NOT EDIT.
cask "skillet" do
  name "skillet"
  desc "Run Agent SKILL.md files as shell commands with Claude Code"
  homepage "https://github.com/martinemde/skillet"
  version "0.2.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "skillet"

  on_macos do
    on_intel do
      url "https://github.com/martinemde/skillet/releases/download/v#{version}/skillet_Darwin_x86_64.tar.gz"
      sha256 "a2dd5c2979f1018e3122127f34544852e832a8e8962b2bdf8f721d27e99a1e82"
    end
    on_arm do
      url "https://github.com/martinemde/skillet/releases/download/v#{version}/skillet_Darwin_arm64.tar.gz"
      sha256 "f9e531624f563f8247bc97afba138c068adf6d03fc343231d1575f1721e1d84e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/martinemde/skillet/releases/download/v#{version}/skillet_Linux_x86_64.tar.gz"
      sha256 "e8fb44d12f7e92f46547b4d0adfd1f1c589bddb26859a42b359a23359c930738"
    end
    on_arm do
      url "https://github.com/martinemde/skillet/releases/download/v#{version}/skillet_Linux_arm64.tar.gz"
      sha256 "985f1aed757eb6b355837ef5ac960d4d3b22b5a9debfd5d8baad4a97ec23f132"
    end
  end

  # No zap stanza required
end
