# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skillet < Formula
  desc "Run Agent SKILL.md files as shell commands with Claude Code"
  homepage "https://github.com/martinemde/skillet"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/martinemde/skillet/releases/download/v0.3.1/skillet_Darwin_x86_64.tar.gz"
      sha256 "19d633928a6e1b63ae586f545dbff4407a6968f8afcca69f666f81abad97bb3e"

      def install
        bin.install "skillet"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/martinemde/skillet/releases/download/v0.3.1/skillet_Darwin_arm64.tar.gz"
      sha256 "6aced36c5bdf78256a4663589a231b2e4c10f57d36c9d7969a4518db97e3de9c"

      def install
        bin.install "skillet"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/martinemde/skillet/releases/download/v0.3.1/skillet_Linux_x86_64.tar.gz"
      sha256 "5594fe9001048fb997df1ec0522b7216edfea0deed02464a2de9b78169395bdd"
      def install
        bin.install "skillet"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/martinemde/skillet/releases/download/v0.3.1/skillet_Linux_arm64.tar.gz"
      sha256 "ec006b5b61044822ca5c6940cb2523bbdce1e25389a93f669ba1b0b22b90ca9e"
      def install
        bin.install "skillet"
      end
    end
  end

  test do
    system "#{bin}/skillet", "--version"
  end
end
