# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Skillet < Formula
  desc "Run Agent SKILL.md files as shell commands with Claude Code"
  homepage "https://github.com/martinemde/skillet"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/martinemde/skillet/releases/download/v0.4.0/skillet_Darwin_x86_64.tar.gz"
      sha256 "e5baf82925bccdde172b646d5cb89988cf00407d660e7ee7956c7db8642046e8"

      def install
        bin.install "skillet"
        bash_completion.install "completions/skillet.bash" => "skillet"
        zsh_completion.install "completions/_skillet"
        fish_completion.install "completions/skillet.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/martinemde/skillet/releases/download/v0.4.0/skillet_Darwin_arm64.tar.gz"
      sha256 "ba555e680ca8118d0bbdd91e8a437ae01938991caec16ef5dd769e836689c61e"

      def install
        bin.install "skillet"
        bash_completion.install "completions/skillet.bash" => "skillet"
        zsh_completion.install "completions/_skillet"
        fish_completion.install "completions/skillet.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/martinemde/skillet/releases/download/v0.4.0/skillet_Linux_x86_64.tar.gz"
      sha256 "27b088771674907f49d365ae38dff0aa2bc0320fdce66d153b36d4e7d4411235"
      def install
        bin.install "skillet"
        bash_completion.install "completions/skillet.bash" => "skillet"
        zsh_completion.install "completions/_skillet"
        fish_completion.install "completions/skillet.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/martinemde/skillet/releases/download/v0.4.0/skillet_Linux_arm64.tar.gz"
      sha256 "21b59caad5865973a5a6d9bd2278bdd34ecb297110a97497475cf5b43c755e9f"
      def install
        bin.install "skillet"
        bash_completion.install "completions/skillet.bash" => "skillet"
        zsh_completion.install "completions/_skillet"
        fish_completion.install "completions/skillet.fish"
      end
    end
  end

  test do
    system "#{bin}/skillet", "--version"
  end
end
